// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type User = {
    id?: number;
    username?: string;
    password?: string;
    nickname?: string;
    schoolId?: string;
    role?: number;
    avatar?: string;
    status?: number;
    createTime?: string;
    updateTime?: string;
    delFlag?: number;
};

export type ApiResponse = {
    code?: number;
    message?: string;
    data?: unknown;
};

export type ApiResponseUser = {
    code?: number;
    message?: string;
    data?: User;
};

export type OrderItem = {
    column?: string;
    asc?: boolean;
};

export type PageUser = {
    records?: Array<User>;
    total?: number;
    size?: number;
    current?: number;
    /**
     * @deprecated
     */
    pages?: number;
};

export type ApiResponseIPageUser = {
    code?: number;
    message?: string;
    data?: IPageUser;
};

export type IPageUser = {
    size?: number;
    records?: Array<User>;
    current?: number;
    /**
     * @deprecated
     */
    pages?: number;
    total?: number;
};

export type PageUserWritable = {
    records?: Array<User>;
    total?: number;
    size?: number;
    current?: number;
    orders?: Array<OrderItem>;
    optimizeCountSql?: PageUserWritable;
    searchCount?: PageUserWritable;
    optimizeJoinOfCountSql?: boolean;
    maxLimit?: number;
    countId?: string;
    /**
     * @deprecated
     */
    pages?: number;
};

export type UpdateUserData = {
    body: User;
    path?: never;
    query?: never;
    url: '/updateUser';
};

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: ApiResponse;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type RegisterUserData = {
    body: User;
    path?: never;
    query?: never;
    url: '/register';
};

export type RegisterUserResponses = {
    /**
     * OK
     */
    200: ApiResponse;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type LoginUserData = {
    body: User;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginUserResponses = {
    /**
     * OK
     */
    200: ApiResponseUser;
};

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];

export type GetUserListData = {
    body?: never;
    path?: never;
    query: {
        page: PageUserWritable;
    };
    url: '/getUserList';
};

export type GetUserListResponses = {
    /**
     * OK
     */
    200: ApiResponseIPageUser;
};

export type GetUserListResponse = GetUserListResponses[keyof GetUserListResponses];

export type DeleteUserData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/';
};

export type DeleteUserResponses = {
    /**
     * OK
     */
    200: ApiResponse;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/getUser';
};

export type GetUserResponses = {
    /**
     * OK
     */
    200: ApiResponseUser;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];
